org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true


parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17


minecraft_version=1.21.1

minecraft_version_range=[1.21.1]

neo_version=21.1.128

loader_version_range=[1,)

mod_id=votestopserver

mod_name=Vote Stop Server

mod_license=All Rights Reserved

mod_version=1.20.1-0.0.6-forge


mod_group_id=net.lanzr.votestopserver

mod_authors=Lanzr

mod_description=A mod where players vote to decide whether to shut down the server